### PR TITLE
Code cleanups for Go

### PR DESCRIPTION
**Pull request by abenz1267**
Just some fixes for the Go code.

### CODE REVIEW

**Comment by abenz1267** [comment]
Ok, i've only gone through a few files for now...

removing variables that are only used once is quite opinionated, I know. Feel free to not do that. Besides that i found some highly questionable code, as in: why wouldn't you use `filepath.Join` for concatenating a filepath? It's save across OSses and should always be used over simply concatenating strings.

There were also 2 functions that literally just wrapped other functions with the same signature without doing anything else. Those functions haven't even been called anywhere else... not quite sure what the intention here was. Simply having different naming for `starting` and `adding`? Not sure if this serves any purpose.

Overall i'm not quite sure what to think about this. The variable naming is imo questionable as well. Naming sessions `ss` and a map of sessions `ssm` is quite eye-brow-raising for an open source project I think, as f.e. I literally had to look up what I'm getting there.

Kind Regards

**Comment by hsluoyz** [comment]
lgtm

**Comment by abh** [comment]
if you are going to be nit-picky then util/setting.go also uses CacheDir + mouselog (so the three instances of that could probably be put into a function together).

**Comment by hsluoyz** [comment]
@abh can you make a PR about it?

**Comment by abh** [comment]
@hsluoyz I'm not sure I can do the CLA hoops, so I'll leave it for others to do. :-)

**Pull request merged**
